version: '3'

vars:
  MAIN: ./cmd/api/main.go
  ENV_FILE: .env

tasks:
  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - go test ./...

  # usage: FILTER=^TestSomething$ task test:filter
  "test:filter":
    cmds:
      - godotenv -f {{.ENV_FILE}} go test -run $FILTER -v ./...

  "gen:graphql":
    cmds:
      - go run github.com/99designs/gqlgen@v0.17.73 generate

  "gen:models":
    cmds:
      - sqlc generate

  # generate secret token
  "gen:token":
    cmds:
      - go run github.com/moeenn/go-token@latest

  # usage: NAME=create_some_tablle task migration:new    
  "migration:new":
    cmds:
      - goose -s create $NAME sql

  "db:migrate":
    cmds:
      - goose up

  "db:rollback":
    cmds:
      - goose down-to 0

  run:
    cmds:
      - godotenv -f {{.ENV_FILE}} go run {{.MAIN}}

  "build:run":
    cmds:
      - task: "gen:models"
      - task: "gen:graphql"
      - task: run

  build:
    cmds:
      - task: lint
      - task: test
      - task: "gen:models"
      - task: "gen:graphql"
      - go build -o ./bin/api {{.MAIN}}
