version: '3'

vars:
  MAIN: ./cmd/api/main.go
  ENV_FILE: .env

tasks:
  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - go test ./...

  # usage: FILTER=^TestSomething$ task test:filter
  "test:filter":
    cmds:
      - godotenv -f {{.ENV_FILE}} go test -run $FILTER -v ./...

  "gen:graphql":
    cmds:
      - go run github.com/99designs/gqlgen@v0.17.73 generate

  "gen:models":
    cmds:
      - sqlc generate

  # generate secret token
  "gen:token":
    cmds:
      - go run github.com/moeenn/go-token@latest
    
  run:
    cmds:
      - godotenv -f {{.ENV_FILE}} go run {{.MAIN}}

  build:
    cmds:
      - task: lint
      - task: test
      - task: "gen:model"
      - task: "gen:graphql"
      - go build -o ./bin/api {{.MAIN}}
