package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"api/graph"
	"api/graph/gmodel"
	"context"

	"github.com/google/uuid"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input gmodel.CreateAccountInput) (*gmodel.MessageResponse, error) {
	return r.Service.CreateAccount(ctx, input)
}

// SetUserDeletedStatus is the resolver for the setUserDeletedStatus field.
func (r *mutationResolver) SetUserDeletedStatus(ctx context.Context, userID uuid.UUID, deleted bool) (*gmodel.MessageResponse, error) {
	return r.Service.SetUserDeletedStatus(ctx, userID, deleted)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit int64, offset int64) (*gmodel.UsersResponse, error) {
	return r.Service.GetAllUsers(ctx, limit, offset)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
